### ISSUE TITLE
profiler not running

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1191]
Looks like it's missing some data files.  Also the `gprof2dot` module should be included in the dev requirements.

**Comment by dlakaplan** [comment]
```(pulsar) kaplan@plock[~/pythonpackages/PINT/profiling] (master) % python run_profile.py bench_load_TOAs.py        
python -m cProfile -o bench_load_TOAs_profile -s time bench_load_TOAs.py
Traceback (most recent call last):
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/cProfile.py", line 190, in <module>
    main()
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/cProfile.py", line 179, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/cProfile.py", line 19, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "bench_load_TOAs.py", line 9, in <module>
    thanktoas = pint.toa.get_TOAs(
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/pint/toa.py", line 258, in get_TOAs
    t = TOAs(timfile)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/pint/toa.py", line 1265, in __init__
    toalist, self.commands = read_toa_file(toafile)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/pint/toa.py", line 690, in read_toa_file
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'J0740+6620.cfr+19.tim'
/bin/sh: dot: command not found
Traceback (most recent call last):
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/bin/gprof2dot", line 8, in <module>
    sys.exit(main())
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/gprof2dot.py", line 3551, in main
    dot.graph(profile, theme)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/gprof2dot.py", line 3252, in graph
    self.edge(function.id, call.callee_id,
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/gprof2dot.py", line 3287, in edge
    self.attr_list(attrs)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/gprof2dot.py", line 3302, in attr_list
    self.id(name)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/gprof2dot.py", line 3317, in id
    self.write(s)
  File "/Users/kaplan/opt/anaconda3/envs/pulsar/lib/python3.9/site-packages/gprof2dot.py", line 3341, in write
    self.fp.write(s)
BrokenPipeError: [Errno 32] Broken pipe
Thu Mar 31 10:42:31 2022    bench_load_TOAs_profile

         3830078 function calls (3796668 primitive calls) in 1.855 seconds

   Ordered by: internal time
   List reduced from 4935 to 100 due to restriction <100>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   108/80    0.209    0.002    0.430    0.005 {built-in method _imp.create_dynamic}
        2    0.134    0.067    0.776    0.388 core.py:1292(read)
        1    0.122    0.122    0.122    0.122 {built-in method mkl._py_mkl_service.get_version}
    40377    0.106    0.000    0.242    0.000 fixedwidth.py:41(<listcomp>)
    40377    0.102    0.000    0.102    0.000 fixedwidth.py:39(<listcomp>)
   793248    0.095    0.000    0.136    0.000 core.py:398(process_val)
      672    0.088    0.000    0.088    0.000 {method 'read' of '_io.BufferedReader' objects}
     1336    0.081    0.000    0.081    0.000 {built-in method numpy.array}
     5403    0.080    0.000    0.080    0.000 core.py:874(<genexpr>)
   795479    0.042    0.000    0.042    0.000 {method 'strip' of 'str' objects}
      646    0.037    0.000    0.037    0.000 {built-in method marshal.loads}
   862071    0.036    0.000    0.036    0.000 {method 'append' of 'list' objects}
6485/1500    0.028    0.000    0.034    0.000 copy.py:128(deepcopy)
    40379    0.027    0.000    0.372    0.000 fixedwidth.py:37(__call__)
     4492    0.023    0.000    0.023    0.000 {built-in method posix.stat}
      646    0.020    0.000    0.020    0.000 {built-in method io.open_code}
   108/93    0.018    0.000    0.059    0.001 {built-in method _imp.exec_dynamic}
     6262    0.018    0.000    0.018    0.000 {built-in method posix.lstat}
     3707    0.016    0.000    0.016    0.000 core.py:1808(_inject)
 1369/267    0.015    0.000    0.041    0.000 sre_parse.py:493(_parse)
        1    0.015    0.015    0.015    0.015 linalg.py:2169(lstsq)
1703/1692    0.015    0.000    0.151    0.000 {built-in method builtins.__build_class__}
     1047    0.011    0.000    0.012    0.000 sre_compile.py:276(_optimize_charset)
      352    0.010    0.000    0.010    0.000 {built-in method builtins.compile}
      308    0.010    0.000    0.010    0.000 {built-in method posix.listdir}
8244/2202    0.009    0.000    0.066    0.000 core.py:1971(__call__)
   133036    0.009    0.000    0.010    0.000 {built-in method builtins.isinstance}
      152    0.008    0.000    0.053    0.000 core.py:2406(_add_prefixes)
     8015    0.007    0.000    0.011    0.000 posixpath.py:71(join)
       56    0.007    0.000    0.007    0.000 {method 'splitlines' of 'str' objects}
    28703    0.007    0.000    0.007    0.000 sre_parse.py:233(__next)
      291    0.007    0.000    0.007    0.000 data_info.py:547(__init__)
     1031    0.007    0.000    0.010    0.000 copy.py:258(_reconstruct)
1803/1773    0.007    0.000    0.017    0.000 core.py:2301(_expand_and_gather)
 2318/242    0.007    0.000    0.020    0.000 sre_compile.py:71(_compile)
116545/113766    0.006    0.000    0.007    0.000 {built-in method builtins.len}
     1159    0.006    0.000    0.033    0.000 <frozen importlib._bootstrap_external>:1505(find_spec)
5431/5401    0.006    0.000    0.026    0.000 core.py:2227(__init__)
31123/30962    0.005    0.000    0.007    0.000 {built-in method builtins.getattr}
      682    0.005    0.000    0.005    0.000 {method '__exit__' of '_io._IOBase' objects}
     3707    0.005    0.000    0.029    0.000 core.py:1703(__init__)
        1    0.005    0.005    0.005    0.005 {method 'sort' of 'numpy.ndarray' objects}
    24168    0.005    0.000    0.010    0.000 sre_parse.py:254(get)
  561/560    0.004    0.000    0.035    0.000 posixpath.py:397(_joinrealpath)
       91    0.004    0.000    0.007    0.000 transformations.py:57(frame_comps_from_set)
     1222    0.004    0.000    0.006    0.000 posixpath.py:334(normpath)
       12    0.004    0.000    0.006    0.000 {method 'read' of '_io.TextIOWrapper' objects}
    27771    0.004    0.000    0.004    0.000 {method 'startswith' of 'str' objects}
      162    0.004    0.000    0.007    0.000 inspect.py:626(cleandoc)
        7    0.004    0.001    0.033    0.005 core.py:180(add_enabled_units)
      242    0.004    0.000    0.009    0.000 utils.py:36(_iter_unit_summary)
22188/22142    0.004    0.000    0.009    0.000 {built-in method builtins.hasattr}
     3366    0.004    0.000    0.021    0.000 core.py:666(_get_physical_type_id)
    15563    0.003    0.000    0.005    0.000 sre_parse.py:164(__getitem__)
        3    0.003    0.001    0.004    0.001 helpers.py:218(validate)
5158/4036    0.003    0.000    0.016    0.000 core.py:2348(decompose)
   1030/1    0.003    0.000    1.856    1.856 {built-in method builtins.exec}
     8780    0.003    0.000    0.004    0.000 core.py:867(__hash__)
      646    0.003    0.000    0.168    0.000 <frozen importlib._bootstrap_external>:916(get_code)
     6338    0.003    0.000    0.008    0.000 <frozen importlib._bootstrap_external>:121(_path_join)
     6338    0.003    0.000    0.004    0.000 <frozen importlib._bootstrap_external>:123(<listcomp>)
 2805/764    0.003    0.000    0.004    0.000 sre_parse.py:174(getwidth)
      786    0.003    0.000    0.044    0.000 <frozen importlib._bootstrap>:901(_find_spec)
  329/240    0.003    0.000    0.027    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
    22417    0.003    0.000    0.008    0.000 {method 'add' of 'set' objects}
      594    0.003    0.000    0.008    0.000 version.py:205(_legacy_cmpkey)
     6436    0.003    0.000    0.004    0.000 version.py:187(_parse_version_parts)
2944/2212    0.002    0.000    0.012    0.000 {built-in method __new__ of type object at 0x105068a40}
     1292    0.002    0.000    0.007    0.000 <frozen importlib._bootstrap_external>:361(cache_from_source)
12136/12132    0.002    0.000    0.003    0.000 {method 'join' of 'str' objects}
      125    0.002    0.000    0.002    0.000 {built-in method posix.getcwd}
    25276    0.002    0.000    0.002    0.000 core.py:1780(name)
        1    0.002    0.002    0.002    0.002 {method 'dot' of 'numpy.ndarray' objects}
    27237    0.002    0.000    0.002    0.000 {method 'update' of 'set' objects}
    34708    0.002    0.000    0.002    0.000 {method 'get' of 'dict' objects}
       84    0.002    0.000    0.055    0.001 inspect.py:727(getmodule)
    811/1    0.002    0.000    1.856    1.856 <frozen importlib._bootstrap>:1002(_find_and_load)
15246/15243    0.002    0.000    0.006    0.000 core.py:2174(__hash__)
     3681    0.002    0.000    0.032    0.000 core.py:2154(__init__)
        4    0.002    0.001    0.003    0.001 codata.py:1498(parse_constants_2002to2014)
    14303    0.002    0.000    0.002    0.000 {method 'endswith' of 'str' objects}
     3503    0.002    0.000    0.003    0.000 core.py:1741(_generate_doc)
     6262    0.002    0.000    0.020    0.000 posixpath.py:164(islink)
      998    0.002    0.000    0.005    0.000 version.py:271(__init__)
      774    0.002    0.000    0.002    0.000 {method 'sub' of 're.Pattern' objects}
     4372    0.002    0.000    0.004    0.000 {method 'format' of 'str' objects}
      761    0.002    0.000    0.010    0.000 <frozen importlib._bootstrap>:486(_init_module_attrs)
     5818    0.002    0.000    0.003    0.000 <frozen importlib._bootstrap>:398(parent)
     1431    0.002    0.000    0.003    0.000 <frozen importlib._bootstrap>:166(_get_module_lock)
       53    0.002    0.000    2.002    0.038 __init__.py:1(<module>)
 1020/242    0.002    0.000    0.042    0.000 sre_parse.py:435(_parse_sub)
     1089    0.002    0.000    0.003    0.000 functools.py:35(update_wrapper)
3213/2260    0.002    0.000    0.004    0.000 column.py:1070(__setattr__)
        4    0.002    0.000    0.002    0.000 {built-in method _functools.reduce}
     1431    0.002    0.000    0.002    0.000 <frozen importlib._bootstrap>:87(acquire)
    761/2    0.002    0.000    1.856    0.928 <frozen importlib._bootstrap>:659(_load_unlocked)
        6    0.002    0.000    0.002    0.000 {method 'read' of '_io.FileIO' objects}
     1854    0.002    0.000    0.075    0.000 re.py:289(_compile)
      819    0.002    0.000    0.002    0.000 {method 'split' of 're.Pattern' objects}
      646    0.002    0.000    0.115    0.000 <frozen importlib._bootstrap_external>:1036(get_data)
```

**Comment by dlakaplan** [comment]
Maybe we need a README in that directory too

**Comment by paulray** [comment]
Yes, for sure. I thought there was one but it is not there...

**Comment by paulray** [comment]
Do you know what is wrong with the gridding?
```
 % py bench_chisq_grid.py
/Users/paulr/src/PINT-nanograv/src/pint/models/timing_model.py:366: UserWarning: PINT only supports 'T2CMETHOD IAU2000B'
  warn("PINT only supports 'T2CMETHOD IAU2000B'")
Traceback (most recent call last):
  File "/Users/paulr/src/PINT/profiling/bench_chisq_grid.py", line 36, in <module>
    thankftr_chi2grid = grid_chisq(thankftr, "M2", m2_grid, "SINI", sini_grid)
  File "/Users/paulr/src/PINT-nanograv/src/pint/gridutils.py", line 165, in grid_chisq
    getattr(ftr.model, parname).frozen = True
  File "/Users/paulr/src/PINT-nanograv/src/pint/models/timing_model.py", line 393, in __getattr__
    raise AttributeError(
AttributeError: Attribute M not found in TimingModel or any Component
```

**Comment by dlakaplan** [comment]
Change it to:
```
thankftr_chi2grid = grid_chisq(thankftr, ("M2","SINI"), (m2_grid,sini_grid),ncpu=1)
```
(the interface changed, and this explicitly uses a single CPU so that you don't have any multiprocessing issues)

**Comment by paulray** [comment]
Thanks, PR coming...

**Comment by dlakaplan** [comment]
I suggest that you add the tim file to one of the relevant places within PINT itself so it doesn't need to be downloaded separately.  Files from Emmanuel's paper are already in there:
```
pint.config.examplefile("J0740+6620.FCP+21.wb.DMX3.0.par")
pint.config.examplefile("J0740+6620.FCP+21.wb.tim")
```

**Comment by paulray** [comment]
I could do that but Thankful's tim file is large (3.5 MB). Is that OK to add?

**Comment by dlakaplan** [comment]
I guess Emmanuel's is WB so it's smaller.

But there are other 1 MB files.  don't know what the threshold should be (or if it's better to use a different data-set - not sure if longitudinal testing is really needed here).
