### ISSUE TITLE
photonphase with --addphase crashes

### ISSUE THREAD

**Issue by sguillot** [nanograv/PINT#1207]
Hi,

The script photonphase with the `--addphase` option (to add the PULSE_PHASE column in the original fits file) crashes, possibly due to an `astropy` incompatibility (see below). It is working fine if instead of using `--addphase`, the PULSE_PHASE column is added into a new output file (with `--outfile`). This is with `python 3.9.5` and `astropy 4.3.1`.

```
Traceback (most recent call last):
  File "/home/sguillot/Softwares/miniconda3/bin/photonphase", line 8, in <module>
    sys.exit(main())
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/pint/scripts/photonphase.py", line 213, in main
    mjds_float = read_fits_event_mjds(hdulist[1])
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/pint/fits_utils.py", line 85, in read_fits_event_mjds
    event_dat = event_hdu.data
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/astropy/utils/decorators.py", line 767, in __get__
    val = self.fget(obj)
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/astropy/io/fits/hdu/table.py", line 402, in data
    data = self._get_tbdata()
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/astropy/io/fits/hdu/table.py", line 172, in _get_tbdata
    raw_data = self._get_raw_data(self._nrows, columns.dtype,
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/astropy/io/fits/hdu/base.py", line 529, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/home/sguillot/Softwares/miniconda3/lib/python3.9/site-packages/astropy/io/fits/file.py", line 300, in readarray
    self._mmap = mmap.mmap(self._file.fileno(), 0,
OSError: [Errno 22] Invalid argument
```

**Comment by paulray** [comment]
Strange. I use `--addphase` all the time with no issues.

**Comment by paulray** [comment]
I wonder if we should consider adding a requirements.txt to define what versions of various packages we are compatible with?

**Comment by paulray** [comment]
Could this just be an error caused by a huge event file?

**Comment by paulray** [comment]
Can you give me the exact command line that fails? Also, can you reproduce with one of the data files included with PINT? That would make it easy to test.

**Comment by paulray** [comment]
In particular, this command works for me:
```
cd tests/datafile
photonphase --addphase ngc300nicer_bary.evt ngc300nicer.par
```
This is on Ubuntu:
```
% uname -a
Linux hesenode1 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
% python --version
Python 3.8.10
```

**Comment by paulray** [comment]
Also, 0.8.4 is pretty old now. I don't think it will affect this issue but please update to at least 0.8.5, or the latest dev version.

**Comment by sguillot** [comment]
With your suggestions, I've managed to track down the problem. 
On our Ubuntu machines, the command
`photonphase --addphase ngc300nicer_bary.evt ngc300nicer.par`
works when the files are in my home directory.
But if I put the files in the mounted data drive, it doesn't work anymore (see error in my original post); and 
`photonphase --addphase ngc300nicer_bary.evt ngc300nicer.par --outfile ngc300_out.evt` works fine.

This is really weird because I have full writing access to the data directory.
It seems to be an astropy issue anyway.
