### ISSUE TITLE
"Fitting" START/FINISH failure

### ISSUE THREAD

**Issue by bwmeyers** [nanograv/PINT#1237]
I mentioned this originally in #1203 but it turns out to probably be a separate issue. I'll copy-paste the text here for easier tracking.

I ran into this when trying this out on some CHIME data with a tempo2-generated parfile: the START and FINISH keys are set and, for whatever reason, are followed by 1 0.0, e.g.,
```
START              59030.5932034769185710 1 0.0
FINISH             59328.7824288187154490 1 0.0
```
and I think this makes PINT try to "fit" them, or at least it does in pintk. I get the following error -
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/pintk/plk.py", line 459, in fit
    self.fit_callback()
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/pintk/plk.py", line 664, in fit
    self.psr.fit(self.selected)
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/pintk/pulsar.py", line 372, in fit
    fitter.fit_toas(maxiter=1)
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/fitter.py", line 1933, in fit_toas
    M, params, units = self.get_designmatrix()
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/fitter.py", line 583, in get_designmatrix
    return self.model.designmatrix(toas=self.toas, incfrozen=False, incoffset=True)
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/models/timing_model.py", line 1729, in designmatrix
    q = -self.d_phase_d_param(toas, delay, param)
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/models/timing_model.py", line 1565, in d_phase_d_param
    d_delay_d_p = self.d_delay_d_param(toas, param)
  File "/home/bmeyers/gbncc/venv/lib/python3.8/site-packages/pint/models/timing_model.py", line 1578, in d_delay_d_param
    raise AttributeError(
AttributeError: Derivative function for 'START' is not provided or not registered.
```
Which is fine, because it's obviously not supposed to be including START/FINISH in the timing model fit, but I feel like those should maybe be ignored or fixed and have a WARNING message, rather than cause the whole process to fail?

Attached is an example par/tim file that reproduces this error for me.
[example.tar.gz](https://github.com/nanograv/PINT/files/8665030/example.tar.gz)

**Comment by aarchiba** [comment]
Perhaps parameter objects should be able to be set as never fittable when constructed? Then it would squawk if a par file or other code tried to make them fittable, and we could ensure we never output par files that ask for them to be fit.

**Comment by aarchiba** [comment]
Perhaps parameter objects should be able to be set as never fittable when constructed? Then it would squawk if a par file or other code tried to make them fittable, and we could ensure we never output par files that ask for them to be fit.

**Comment by bwmeyers** [comment]
I can confirm now that if I load in the provided example par file, then (at least from the output of pintk) it shows up as 
```
START              59030.5932034769185710 0 0.0
FINISH             59328.7824288187154490 0 0.0
```
and fitting doesn't break anymore. They are also written out in the final par file with the trailing `0  0.0`, so I'd say it's solved :)
