### ISSUE TITLE
I'm having some problems with Command-line tools

### ISSUE THREAD

**Issue by zzzlllccc** [nanograv/PINT#1255]
When I use Command-line tools, I encounter errors that I do not understand, I hope someone can give me some help, thanks very much

Here is what I encountered

(base) zlc@zlc-Precision-3440:~/datafile$ photonphase --plot B1509_RXTE_short.fits J1513-5908_PKS_alldata_white.par --orbfile FPorbit_Day6223
Traceback (most recent call last):
  File "/home/zlc/anaconda3/bin/photonphase", line 5, in <module>
    from pint.scripts.photonphase import main
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/pint/scripts/photonphase.py", line 26, in <module>
    from pint.plot_utils import phaseogram_binned
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/pint/plot_utils.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 1925, in <module>
    GlueSpec._types = {k: GlueSpec(**v._asdict())
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 1925, in <dictcomp>
    GlueSpec._types = {k: GlueSpec(**v._asdict())
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 233, in wrapper
    _warn_external(warning)
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 2108, in _warn_external
    warnings.warn(message, category, stacklevel)
  File "/home/zlc/anaconda3/lib/python3.8/site-packages/pint/logging.py", line 99, in warn
    and (msg.match(message) and len(args) == 0)
**TypeError: expected string or bytes-like object**

**Comment by scottransom** [comment]
This was fixed a couple days ago bu commit c2a07c116.  If you have installed the source via git, please do a "git pull".   If you used the tagged version from PyPI, let us know and we can update that.

**Comment by dlakaplan** [comment]
And now I think that fix should be updated on PyPI (now) and conda (shortly).

**Comment by zzzlllccc** [comment]
Thanks for your replies, I have now reinstalled pint through the source code on github.And solved the problem.
