### ISSUE TITLE
pintk fails when .tim file is in a subdir

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1289]
The file exists and this runs fine if I copy the .tim file to my current dir.  Somehow it is losing the first part of the path. Probably a consequence of the change to pathlib?
```
% pintk pintecc.par QL1/split/split0000.tim
Traceback (most recent call last):
  File "/Users/paulr/env/pint/bin/pintk", line 33, in <module>
    sys.exit(load_entry_point('pint-pulsar', 'console_scripts', 'pintk')())
  File "/Users/paulr/src/PINT/src/pint/scripts/pintk.py", line 264, in main
    app = PINTk(
  File "/Users/paulr/src/PINT/src/pint/scripts/pintk.py", line 54, in __init__
    self.openPulsar(
  File "/Users/paulr/src/PINT/src/pint/scripts/pintk.py", line 156, in openPulsar
    self.psr = Pulsar(parfile, timfile, ephem, fitter=fitter)
  File "/Users/paulr/src/PINT/src/pint/pintk/pulsar.py", line 83, in __init__
    self.all_toas = get_TOAs(self.timfile, model=self.prefit_model, usepickle=True)
  File "/Users/paulr/src/PINT/src/pint/toa.py", line 231, in get_TOAs
    if not t.check_hashes():
  File "/Users/paulr/src/PINT/src/pint/toa.py", line 1765, in check_hashes
    if _compute_hash(t) != self.hashes[f]:
  File "/Users/paulr/src/PINT/src/pint/toa.py", line 101, in _compute_hash
    h.update(open(filename, "rb").read())
FileNotFoundError: [Errno 2] No such file or directory: 'split0000.tim'
```

**Comment by aarchiba** [comment]
Surely pickles shouldn't rely on your current directory?
