### ISSUE TITLE
pintk crashes when selecting the last TOA

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1290]
This I can replicate with NGC6440E.par/tim
Start pintk and switch X-axis to "index" (this is not necessary but for NGC6440E it makes it easier because the last two TOAs are very close to each other).
Select a random TOA with left click and hit "d" to delete it. Now try to select that last TOA. I get this:
```
Traceback (most recent call last):
  File "/Users/paulr/env/pint/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/Users/paulr/src/PINT/src/pint/pintk/plk.py", line 1329, in canvasReleaseEvent
    self.stationaryClick(event)
  File "/Users/paulr/src/PINT/src/pint/pintk/plk.py", line 1358, in stationaryClick
    self.selected[ind] = not self.selected[ind]
IndexError: index 61 is out of bounds for axis 0 with size 61
```

**Comment by aarchiba** [comment]
I haven't tracked it down yet, but both `pint.pintk.pulsar.Pulsar` and `pint.pintk.plk.PlkWidget` maintain a list of selected TOAs, and it seems likely that these are getting out of sync. I don't see why this should be - that list should live only in the GUI-free `pint.pintk.pulsar.Pulsar` - and abolishing the one in `pint.pintk.plk.PlkWidget` should fix that and probably other headaches.

**Comment by aarchiba** [comment]
Good God, `pint.pintk.pulsar.Pulsar` has an internal list of selected TOAs but every function that can act on a subset of TOAs *also* accepts a `selected` argument; how that is supposed to relate to the `selected_toas` internally is unclear but I think they're supposed to always be the same.

**Comment by scottransom** [comment]
For your last two comments, those two things are different, but similar.  And I think they are both required.  The `Pulsar` one is a subset of the full TOAs object, and the `plk` one is a boolean array that simply indicates if the user has drawn a box around (or clicked on) TOAs/residuals in the gui.  That latter one is passed to important routines in Pulsar that update things *for those gui-selected points*, that do not necessarily correspond to the set of selected TOAs that you (maybe) have just fitted.  For instance, you can fit a subset of TOAs, and in that process the two objects end up being the same.  But if you then gui-select some of those TOAs to have a JUMP added, they are not the same anymore.  Maybe there is a better way to do this, but there will always need to be at least some kind of temporary list/array that says which points the user has grabbed in the gui.

Note that I'm *swamped* with things until Monday morning, but I'm happy to work on `pintk` issues after that.  Remember that most of the code in `pintk` was written by 3 different undergraduates over the course of a couple years, and virtually no one was using it!

**Comment by scottransom** [comment]
Maybe it is possible to make the `Pulsar` `selected_toas` go away completely now that fancy indexing works on our TOAs objects?

**Comment by aarchiba** [comment]
My preference is to move all state into the Pulsar object so that (for example) the steps Paul describes could be carried out in a test case on a Pulsar object. I started trying to do this and got lost in the three different notions of "selected" (resident in Pulsar, passed into Pulsar functions, and resident in the GUI bit). If the GUI needs to know what to highlight, it can query the Pulsar object. 

If there need to be two different notions of "selected", can we distinguish them by giving them different names, rather than by having them in two different places? (Do we have a fourth notion with "stashing"?)

**Comment by scottransom** [comment]
Note that I *think* this is a purely gui issue, based on the interaction of the mouse-based selection and plotted points with the internal TOA structure.  So I suspect that #1299 won't help with testing for this issue.  I haven't figured out exactly where the problem is, but I think it is because we are querying matplotlib for the nearest points and they are stale (for some reason) in matplotlib.

**Comment by scottransom** [comment]
@paulray Are you sure that you are able to replicate this *without* going into "serial" plot mode?  I'm only seeing the issue in that mode.  And I can select the final (in MJD) TOA just fine after deleting TOAs when it is plotting in MJD mode.

**Comment by paulray** [comment]
Yep, I just tried it again.  Below are a par and tim file. I just run `pintk test.par test.tim`, then select a middle point, hit 'd' to delete it, then try to select the last TOA.
```
PSRJ                           J1956+0326
EPHEM                               DE421
CLK                               TT(TAI)
UNITS                                 TDB
START              59749.6266657155131664
FINISH             59749.9590242327748871
TIMEEPH                              FB90
T2CMETHOD                        IAU2000B
DILATEFREQ                              N
DMDATA                                  N
NTOA                                   20
CHI2                    62.09075461633616
RAJ                     19:56:39.11000000
DECJ                     3:26:43.70000000
PMRA                                  0.0
PMDEC                                 0.0
PX                                    0.0
POSEPOCH           59749.6320300000000000
F0                    313.644183194358559 1 1.7368978298993481454e-06
F1                                    0.0
PEPOCH             59749.6320300000000000
TZRMJD             59749.6484245951384955
TZRSITE                                 @
TZRFRQ                                inf
CORRECT_TROPOSPHERE                         N
PLANET_SHAPIRO                          Y
NE_SW                                 0.0
SWM                                   0.0
DM                                    0.0
DM1                                   0.0
DMEPOCH            59749.6320300000000000
BINARY                               ELL1
PB                0.048683844550048459237 1 1.3524813782427484718e-05
A1                   0.016799213413642936 1 5.262188838444807e-05
TASC               59749.6320531714874598 1 2.830169651738051047e-05
EPS1                                  0.0
EPS2                                  0.0
```

```
FORMAT 1
C Created: 2022-06-21T11:06:39.831028
C PINT_version: 0.8.7+312.gcd4a0232
C User: Paul Ray (paulr)
C Host: mcxr2.nrl.navy.mil
C OS: macOS-10.15.7-x86_64-i386-64bit
photon_toa 0.000000 59749.9511201496617134 205.333 @  -nsrc 253.57 -nbkg 6958.43 -exposure 118.77626878023148 -dphi 0.16423 -htest 5.79 -t NICER
photon_toa 0.000000 59749.9524944229948222 112.039 @  -nsrc 249.04 -nbkg 6833.96 -exposure 118.77626875042915 -dphi 0.18046 -htest 7.33 -t NICER
photon_toa 0.000000 59749.9538686950994878 102.712 @  -nsrc 247.95 -nbkg 6804.05 -exposure 118.77626878023148 -dphi 0.11860 -htest 15.88 -t NICER
photon_toa 0.000000 59749.9552436748172028 97.079 @  -nsrc 245.84 -nbkg 6746.16 -exposure 118.77626878023148 -dphi 0.15433 -htest 25.40 -t NICER
photon_toa 0.000000 59749.9566185080453345 90.718 @  -nsrc 255.68 -nbkg 7016.32 -exposure 118.77626875042915 -dphi 0.11180 -htest 13.65 -t NICER
photon_toa 0.000000 59749.9579932019363195 102.774 @  -nsrc 247.21 -nbkg 6783.79 -exposure 118.77626878023148 -dphi 0.15914 -htest 14.40 -t NICER
photon_toa 0.000000 59749.9590242324735172 136.911 @  -nsrc 123.59 -nbkg 3391.41 -exposure 59.38813439011574 -dphi 0.11845 -htest 6.97 -t NICER
```

**Comment by scottransom** [comment]
OK.  I can replicate it with that, but not with the NGC6440E.tim/.par in the tests/datafiles/ directory!

**Comment by paulray** [comment]
Curious!

**Comment by scottransom** [comment]
BTW, if that fixes things, feel free to just make the change and commit it.  I will be unavailable until probably 6-7pm tonight starting now.

**Comment by paulray** [comment]
Yep, that does seem to fix it.

**Comment by scottransom** [comment]
We should make sure that that doesn't screw up selection when you are plotting in non time order (and also if your input .tim file isn't time ordered)...


On June 23, 2022 12:39:26 PM EDT, Paul Ray ***@***.***> wrote:
>Yep, that does seem to fix it.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nanograv/PINT/issues/1290#issuecomment-1164635735
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aarchiba** [comment]
Maybe we need a somewhat efficient look-up-TOA-or-TOAs-by-original-index function? Or just audit uses of the onClick function to ensure they want indices into the current TOA array rather than the original index.

**Comment by scottransom** [comment]
So I just tested that possible fix and I do think that it is working and is correct -- and that it fixes an additional bug where you would accidentally select the wrong point if you are click near any TOA that is after (in index order) any TOAs that have been deleted or stashed.  So I think I'm going to push up that fix, and also move the computation of the "index" value into the `log.debug` call where it is potentially useful (that is one of the ways that I debugged this).
