### ISSUE TITLE
Random Models crashes

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1291]
Just clicking Random Models, then "Fit" crashes like this:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/paulr/src/PINT/src/pint/pintk/plk.py", line 645, in fit
    self.fit_callback()
  File "/Users/paulr/src/PINT/src/pint/pintk/plk.py", line 850, in fit
    self.psr.random_models(self.selected)
  File "/Users/paulr/src/PINT/src/pint/pintk/pulsar.py", line 617, in random_models
    self.faketoas1 = make_fake_toas_uniform(
  File "/Users/paulr/src/PINT/src/pint/simulation.py", line 256, in make_fake_toas_uniform
    ts = pint.toa.TOAs(toalist=t1)
  File "/Users/paulr/src/PINT/src/pint/toa.py", line 1303, in __init__
    self.table = build_table(toalist, filename=self.filename)
  File "/Users/paulr/src/PINT/src/pint/toa.py", line 823, in build_table
    mjds, mjd_floats, errors, freqs, obss, flags = zip(
ValueError: not enough values to unpack (expected 6, got 0)
```
This does not happen on NGC6440E.par/tim, but does for my example. Not sure what is different. This is preliminary data on a pulsar so I don't want to post the par/tim here, but I can provide to developers.

**Comment by paulray** [comment]
OK, I figured this one out. There is some logic in constructing the random models points that is specific to particular use cases and fails when the full dataset is less than one day (as is my case with a new AMXP).  It is an easy fix, but (as is often the case), the error message isn't very helpful. I'll make a PR.
