### ISSUE TITLE
Incompatibility with numpy 1.24.1?

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1494]
It seems that the latest numpy causes PINT to crash.  The crash is shown below (this happens with the simple case of pintempo or pintk on the usual NGC6440E par/tim).

I also notice that numba now restricts to numpy<1.24.  See this message I got from pip:
`numba 0.56.2 requires numpy<1.24,>=1.18, but you have numpy 1.24.1 which is incompatible.`

So, likely there was some non-backwards compatible change starting at numpy 1.24.

The crash below is with numpy 1.24.1 and astropy 5.1 in a virtualenv.

```
% pintempo NGC6440E.par NGC6440E.tim
WARNING  (pint.logging                  ): /Software/miniconda3/envs/hese/lib/python3.10/site-packages/pint/models/timing_model.py:373 UserWarning: PINT only supports 'T2CMETHOD IAU2000B'
WARNING  (pint.scripts.pintempo         ): ['PSR', 'TRACK', 'EPHEM', 'CLOCK', 'UNITS', 'START', 'FINISH', 'RM', 'INFO', 'TIMEEPH', 'T2CMETHOD', 'BINARY', 'DILATEFREQ', 'DMDATA', 'NTOA', 'CHI2', 'TZRMJD', 'TZRSITE', 'TZRFRQ', 'F0', 'PEPOCH', 'F1', 'POSEPOCH', 'PX', 'RAJ', 'DECJ', 'PMRA', 'PMDEC', 'CORRECT_TROPOSPHERE', 'PLANET_SHAPIRO', 'NE_SW', 'SWP', 'SWM', 'DM', 'DM1', 'DMEPOCH']
WARNING  (pint.toa                      ): CLOCK = UTC(NIST) is not implemented. Using TT(BIPM2021) instead.
WARNING  (pint.toa                      ): Unknown command MODE in line MODE 1

Downloading https://raw.githubusercontent.com/ipta/pulsar-clock-corrections/main/index.txt
|=====================================================================================================================| 3.5k/3.5k (100.00%)         0s
Downloading https://raw.githubusercontent.com/ipta/pulsar-clock-corrections/main/T2runtime/clock/gps2utc.clk
|=====================================================================================================================| 303k/303k (100.00%)         0s
Downloading https://raw.githubusercontent.com/ipta/pulsar-clock-corrections/main/T2runtime/clock/tai2tt_bipm2021.clk
|=====================================================================================================================|  77k/ 77k (100.00%)         0s
Downloading https://raw.githubusercontent.com/ipta/pulsar-clock-corrections/main/tempo/clock/time_gbt.dat
|=====================================================================================================================| 396k/396k (100.00%)         0s
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|=====================================================================================================================| 1.3k/1.3k (100.00%)         0s
Downloading https://data.nanograv.org/static/data/ephem/de421.bsp
|=====================================================================================================================|  16M/ 16M (100.00%)         1s
Downloading https://datacenter.iers.org/data/9/finals2000A.all
|=====================================================================================================================| 3.5M/3.5M (100.00%)         7s
Traceback (most recent call last):
  File "/Software/miniconda3/envs/hese/bin/pintempo", line 10, in <module>
    sys.exit(main())
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/pint/scripts/pintempo.py", line 74, in main
    t = pint.toa.get_TOAs(args.timfile, model=m, usepickle=args.usepickle)
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/pint/toa.py", line 304, in get_TOAs
    t.compute_posvels(ephem, planets)
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/pint/toa.py", line 2351, in compute_posvels
    ssb_obs = site.posvel(tdb, ephem)
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/pint/observatory/topo_obs.py", line 426, in posvel
    obs_geocenter_pv = gcrs_posvel_from_itrf(
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/pint/erfautils.py", line 75, in gcrs_posvel_from_itrf
    pos, vel = loc.get_gcrs_posvel(t)
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/astropy/coordinates/earth.py", line 734, in get_gcrs_posvel
    return self._get_gcrs_posvel(obstime,
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/astropy/coordinates/earth.py", line 708, in _get_gcrs_posvel
    pos = itrs_cart.transform(itrs_to_gcrs)
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/astropy/coordinates/representation.py", line 1399, in transform
    p = erfa_ufunc.rxp(matrix, self.get_xyz(xyz_axis=-1))
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/astropy/coordinates/representation.py", line 1351, in get_xyz
    return np.stack([self._x, self._y, self._z], axis=xyz_axis)
  File "<__array_function__ internals>", line 200, in stack
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/astropy/units/quantity.py", line 1683, in __array_function__
    return super().__array_function__(function, types, args, kwargs)
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/numpy/core/shape_base.py", line 471, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out,
  File "<__array_function__ internals>", line 200, in concatenate
  File "/Software/miniconda3/envs/hese/lib/python3.10/site-packages/astropy/units/quantity.py", line 1688, in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)
TypeError: concatenate() got an unexpected keyword argument 'dtype'
```

**Comment by paulray** [comment]
Ah, this is fixed if you use astropy 5.2 instead of astropy 5.1.
But if I go back to astropy 5.0, I get the old `module 'numpy' has no attribute 'asscalar'`

If I go back to numpy 1.23, then it fails with astropy 5.0 but passes with 5.1 and 5.2.

This is kind of a mess.

**Comment by dlakaplan** [comment]
> Ah, this is fixed if you use astropy 5.2 instead of astropy 5.1. But if I go back to astropy 5.0, I get the old `module 'numpy' has no attribute 'asscalar'`
> 
> If I go back to numpy 1.23, then it fails with astropy 5.0 but passes with 5.1 and 5.2.
> 
> This is kind of a mess.

That is kind of an understatement

**Comment by paulray** [comment]
For reference:
https://github.com/astropy/astropy/issues/14210

**Comment by aarchiba** [comment]
Can we check which version of pip is being used? It looks like recent versions of pip do have smart enough dependency resolution: https://pip.pypa.io/en/stable/topics/dependency-resolution/

**Comment by aarchiba** [comment]
We might be able to use `pyproject.toml` to specify "you need at least this version of pip to install": https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies
