### ISSUE TITLE
astropy version for PINT

### ISSUE THREAD

**Issue by nirinA** [nanograv/PINT#3]
what version of astropy should be used with PINT?
i'm trying to run ``tests/test_model.py`` and get the following error:

```
Read/corrected TOAs in 24.739 sec
Computing residuals...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/sda14/nirinA/pint_test_model.py", line 39, in <module>
    p = m.phase(tt)
  File "pint/models/timing_model.py", line 77, in use_cached_results
    result = function(*args, **kwargs)
  File "pint/models/timing_model.py", line 121, in phase
    delay = self.delay(toa)
  File "pint/models/timing_model.py", line 73, in use_cached_results
    return function(*args, **kwargs)
  File "pint/models/timing_model.py", line 140, in delay
    delay += df(toa)
  File "pint/models/solar_system_shapiro.py", line 77, in solar_system_shapiro_delay
    self._ss_mass_sec['sun'])
  File "pint/models/solar_system_shapiro.py", line 51, in ss_obj_shapiro_delay
    rcostheta = obj_pos.dot(psr_dir)
  File "/usr/lib64/python2.7/site-packages/astropy-0.4.dev-py2.7-linux-x86_64.egg/astropy/units/quantity.py", line 1166, in dot
    value = np.dot(self, b, out=out)
ValueError: Cannot find a common data type.

```

nirinA

**Comment by paulray** [comment]
At this point, PINT requires astropy 1.0, or later, but most of the developers use the development version of astropy from github.

**Comment by scottransom** [comment]
Yeah, at least v1.0.  I just added that to the wiki installation page.

**Comment by nirinA** [comment]
the latest astropy from github gives me:
 
```
>>> import pint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pint/__init__.py", line 35, in <module>
    J2000ld = utils.time_to_longdouble(J2000)
  File "/usr/lib64/python2.7/site-packages/pint/utils.py", line 138, in time_to_longdouble
    return np.longdouble(t.jd1-astropy.erfa.DJM0) \
AttributeError: 'module' object has no attribute 'erfa'
>>> import astropy
>>> astropy.version.version
u'1.1.dev'
```
importing `erfa` may be `astropy._erfa` here?
thanks

**Comment by paulray** [comment]
This is fixed in recent PINT versions. Make sure to pull from nanograv/master

**Comment by nirinA** [comment]
ah yes, my PINT fork was sync'ed with https://github.com/scottransom/PINT.git
thanks

**Comment by paulray** [comment]
As I understand, nanograv/PINT is the master, and I think @scottransom develops there.  I'm not sure what scottransom/PINT is for.  Scott?

**Comment by scottransom** [comment]
I was developing in nanograv/PINT, but that was only because noone else really was.  If the number of additional developers continues to increase, I'll start developing in scottransom/PINT instead and do pull-requests like everyone else.
