### ISSUE TITLE
numpy 1.14.0 breaks PINT

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#363]
I just upgraded to numpy 1.14.0 and this caused a bunch of the PINT tests to fail. It seems to be an issue with the ecliptic to ICRS coordinate transformations. All the errors look like this:

```
======================================================================
ERROR: test_K96 (test_ddk.TestDDK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/psray/src/PINT/tests/test_ddk.py", line 75, in test_K96
    res = resids(self.toasJ1713, self.modelJ1713, False).time_resids.to(u.s)
  File "/Users/psray/src/PINT/pint/residuals.py", line 13, in __init__
    self.phase_resids = self.calc_phase_resids(weighted_mean=weighted_mean)
  File "/Users/psray/src/PINT/pint/residuals.py", line 24, in calc_phase_resids
    rs = self.model.phase(self.toas.table)
  File "/Users/psray/src/PINT/pint/models/timing_model.py", line 482, in phase
    delay = self.delay(toas)
  File "/Users/psray/src/PINT/pint/models/timing_model.py", line 476, in delay
    delay += df(toas, delay)
  File "/Users/psray/src/PINT/pint/models/astrometry.py", line 64, in solar_system_geometric_delay
    L_hat = self.ssb_to_psb_xyz_ICRS(epoch=toas['tdbld'].astype(numpy.float64))
  File "/Users/psray/src/PINT/pint/models/astrometry.py", line 49, in ssb_to_psb_xyz_ICRS
    return self.coords_as_ICRS(epoch=epoch).cartesian.xyz.transpose()
  File "/Users/psray/src/PINT/pint/models/astrometry.py", line 382, in coords_as_ICRS
    return pos_ecl.transform_to(coords.ICRS)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/baseframe.py", line 934, in transform_to
    return trans(self, new_frame)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1314, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1232, in __call__
    newrep = self._apply_transform(fromcoord, M, None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1005, in _apply_transform
    rep = rep.transform(matrix)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/representation.py", line 1110, in transform
    newxyz = np.einsum('...ij,j...->i...', matrix, oldxyz.value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/einsumfunc.py", line 1087, in einsum
    einsum_call=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/einsumfunc.py", line 688, in einsum_path
    input_subscripts, output_subscript, operands = _parse_einsum_input(operands)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/einsumfunc.py", line 432, in _parse_einsum_input
    raise TypeError("For this input type lists must contain "
TypeError: For this input type lists must contain either int or Ellipsis
```
Probably something changed with `np.einsum`. I see in the [Release Notes](https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst) that it now tries to use BLAS.

**Comment by scottransom** [comment]
Yeah.  It is almost certainly np.einsum.  There was a major regression with that, and it is affecting a lot of packages.  They are working on a fix.

BTW, when I was reading about these issues a week or two ago, I looked into einsum and it is freaking cool (and super fast).  It is worth trying to use it when possible...

**Comment by paulray** [comment]
I just realized that I'm now using numpy 1.14.2 and I'm not getting any errors, so I think this must have been fixed.

**Comment by matteobachetti** [comment]
I don't know if it's the same problem, but tests of stingray using numpy 1.14 and recent PINT fail with `TypeError: Cannot set fill value of string` 
https://travis-ci.org/StingraySoftware/stingray/jobs/602243780?utm_medium=notification&utm_source=github_status
More recent versions of Numpy don't fail.
