### ISSUE TITLE
Now getting UT1 related error in astropy

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#439]
I'm now getting an error that looks like some malformed data in the IERS data downloaded by astropy.  Here is what I see when I run a simple example from the examples directory:

```
% python fit_NGC6440E.py
WARNING: Unrecognized parfile line 'T2CMETHOD           TEMPO' [pint.models.timing_model]
INFO: Applying clock corrections (include_GPS = True, include_BIPM = True. [pint.toa]
INFO: Observatory gbt, loading clock file /Users/paulr/src/PINT/pint/datafiles/time.dat [pint.observatory.topo_obs]
INFO: Loading tempo observatory (1) clock correction file /Users/paulr/src/PINT/pint/datafiles/time.dat [pint.observatory.clock_file]
INFO: Evaluating observatory clock corrections. [pint.observatory.topo_obs]
INFO: Applying GPS to UTC clock correction (~few nanoseconds) [pint.observatory.topo_obs]
INFO: Observatory gbt, loading GPS clock file /Users/paulr/src/PINT/pint/datafiles/gps2utc.clk [pint.observatory.topo_obs]
INFO: Loading tempo2 observatory clock correction file /Users/paulr/src/PINT/pint/datafiles/gps2utc.clk [pint.observatory.clock_file]
INFO: Applying TT(TAI) to TT(BIPM) clock correction (~27 us) [pint.observatory.topo_obs]
INFO: Observatory gbt, loading BIPM clock file /Users/paulr/src/PINT/pint/datafiles/tai2tt_bipm2015.clk [pint.observatory.topo_obs]
INFO: Loading tempo2 observatory clock correction file /Users/paulr/src/PINT/pint/datafiles/tai2tt_bipm2015.clk [pint.observatory.clock_file]
INFO: Computing TDB columns. [pint.toa]
WARNING: No ephemeris provided to TOAs object or compute_TDBs. Using DE421 [pint.toa]
INFO: Doing astropy mode TDB conversion [pint.observatory.observatory]
INFO: Computing positions and velocities of observatories and Earth (planets = False), using DE421 ephemeris [pint.toa]
Traceback (most recent call last):
  File "fit_NGC6440E.py", line 20, in <module>
    t = pint.toa.get_TOAs(timfile)
  File "/Users/paulr/src/PINT/pint/toa.py", line 63, in get_TOAs
    t.compute_posvels(ephem, planets)
  File "/Users/paulr/src/PINT/pint/toa.py", line 939, in compute_posvels
    ssb_obs = site.posvel(tdb,ephem)
  File "/Users/paulr/src/PINT/pint/observatory/topo_obs.py", line 231, in posvel
    obsname=self.name)
  File "/Users/paulr/src/PINT/pint/erfautils.py", line 69, in gcrs_posvel_from_itrf
    ut1s = np.asarray([(t.jd1, t.jd2) for t in ttoas.ut1]).T
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/time/core.py", line 1125, in __getattr__
    tm._set_scale(attr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/time/core.py", line 496, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/time/core.py", line 1237, in _get_delta_ut1_utc
    iers_table = IERS_Auto.open()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 583, in open
    cls.iers_table = cls.read(file=filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 455, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 417, in _combine_a_b_columns
    is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: invalid literal for int() with base 10: 'N'
```

Anyone else seeing this?

**Comment by paulray** [comment]
Turns out this is a bug in Numpy 1.15.3. Either downgrade to 1.15.2 or upgrade to 1.15.4. That solves it.
