### ISSUE TITLE
'pulsar_mjd' is not used when creating a TOA object from an astropy time object

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#450]
This issue happens when the single TOA object initialized from a astropy.time.Time object. 
```
>>> t1 = time.Time(53410, format='mjd', scale='utc')
>>> test_toa = toa.TOA(t1, obs='gbt', freq=1440)
>>> print(test_toa.mjd.scale)
utc
```
The correct format should be 'pulsar_mjd'

**Comment by paulray** [comment]
Probably if `toa.TOA()` is given a `Time` object with `scale='utc'`, it should fix the format:
`t2 = time.Time(t1,format='pulsar_mjd')`
However, I'm not sure what will happen on a day with a leap second. Probably it will mess things up, but that is the danger of using MJDs to express UTC times.

**Comment by luojing1211** [comment]
That is why we created the "pulsar_mjd". Where do you think the problem could come from, @paulray ?

**Comment by paulray** [comment]
I don't understand your question, exactly.  The problem comes from creating a Time() object with scale utc and format mjd.  That is a bad thing.  Whenever possible, we should avoid creating such objects.  So, the problem is really upstream from PINT (e.g. in the first line of your example above). The right fix is to make sure that upstream code uses format pulsar_mjd. 

Perhaps toa.TOA() should even warn when it is passed a time with scale=utc and format=mjd.

**Comment by luojing1211** [comment]
Sorry, I was not very clear. I meant if we added fix you provide, would there be more problem? But I see your point, one should not write a line as the first line I provided.  This is such a detail that a user may easily forget. I think providing some warning would be nice. But on the other hand, PINT already prints a lot of warning.

**Comment by paulray** [comment]
I do not know what will happen if you use my fix.  On all non leap-second days it should do nothing. We should test it on a leap second day.

**Comment by matteobachetti** [comment]
Is this related to recent failures like this in photonphase and others, or should I open an additional issue?
```
Traceback (most recent call last):
  File "/Users/meo/anaconda/envs/py3/bin/photonphase", line 11, in <module>
    sys.exit(main())
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/scripts/photonphase.py", line 99, in main
    modelin = pint.models.get_model(args.parfile)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/model_builder.py", line 255, in get_model
    mb = ModelBuilder(parfile)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/model_builder.py", line 52, in __init__
    self.build_model(self.parfile, self.name)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/model_builder.py", line 225, in build_model
    self.timing_model.read_parfile(parfile)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/timing_model.py", line 814, in read_parfile
    if cmp.__getattr__(par).from_parfile_line(l):
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/parameter.py", line 344, in from_parfile_line_regular
    self.set(k[1])
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/parameter.py", line 295, in set
    self.value = value
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/parameter.py", line 224, in value
    self._quantity = self.set_quantity(val)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/models/parameter.py", line 734, in set_quantity_mjd
    result = time_from_mjd_string(val, self.time_scale)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/pint/utils.py", line 146, in time_from_mjd_string
    precision=9)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/astropy/time/core.py", line 397, in __init__
    precision, in_subfmt, out_subfmt)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/astropy/time/core.py", line 452, in _init_from_vals
    precision, in_subfmt, out_subfmt)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/astropy/time/core.py", line 503, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class pulsar_mjd

```

**Comment by luojing1211** [comment]
Hi Matteo, 
Do you have a timestamp parameter but not in the mjd format?

**Comment by luojing1211** [comment]
That is very interesting. Can I have the parfile? I would like to reproduce the error.

**Comment by matteobachetti** [comment]
```
PSRJ            J0218+4232
NAME            J0218+4232
RAJ             02:18:06.358569          4.000e-06
DECJ            +42:32:17.37515          8.000e-05
ELONG           47.05
ELAT            27.01
DM              61.252                   5.000e-03
PEPOCH          55000
F0              430.461054545748         1.500e-11
F1              -1.434113E-14            1.300e-19
P0              0.00232309053151224      8.000e-17
P1              7.73955E-20              7.000e-25
SURVEY          misc,gbncc
PMRA            5.35                     5.000e-02
PMDEC           -3.74                    1.200e-01
POSEPOCH        55849.1
DMEPOCH         55000.00
F2              2.8E-26                  8.800e-26
BINARY          ELL1
PB              2.02884611561            9.000e-11
ECC             6.8E-6                   4.000e-07
A1              1.9844344                4.000e-07
OM              49                       4.000e-02
TASC            49150.6089170            3.000e-07
EPS1            5.1E-6                   4.000e-07
EPS2            4.5E-6                   4.000e-07
DATE            1995
#UNITS           TCB
```

**Comment by matteobachetti** [comment]
Found it.

`erfa.dtf2d` wants all integers except the seconds. `np.floor` gives floats. So dtf2d fails and the rest with it.
PR coming soon

**Comment by aarchiba** [comment]
This issue seems to be a conflation of a range of different bugs, some of which may have been fixed:

- PINT should signal some kind of warning or error when provided with a Time in UTC and format='mjd'. There should also be test cases on days with leap seconds. 
- Strange failures in photonphase.
- Interpretation of POSEPOCH, DMEPOCH, and so on.
