### ISSUE TITLE
Uninformative error message

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#557]
When I called `fit_toas()` using a model that fit for DM but TOAs from NICER (all infinite frequency), I got the following uninformative error message. Indeed I should not have tried to fit for DM, but the error should be a bit more clear.  I'm not sure where the best place for some kind of check would be.
```
/Users/paulr/src/PINT/src/pint/fitter.py:192: RuntimeWarning: invalid value encountered in true_divide
  M /= fac
Traceback (most recent call last):
  File "/Users/paulr/env/pint/bin/pintempo", line 11, in <module>
    load_entry_point('pint', 'console_scripts', 'pintempo')()
  File "/Users/paulr/src/PINT/src/pint/scripts/pintempo.py", line 57, in main
    f.fit_toas()
  File "/Users/paulr/src/PINT/src/pint/fitter.py", line 199, in fit_toas
    U, s, Vt = sl.svd(M, full_matrices=False)
  File "/Users/paulr/env/pint/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/Users/paulr/env/pint/lib/python3.6/site-packages/scipy/_lib/_util.py", line 239, in _asarray_validated
    a = toarray(a)
  File "/Users/paulr/env/pint/lib/python3.6/site-packages/numpy/lib/function_base.py", line 496, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by paulray** [comment]
This has been fixed.
