### ISSUE TITLE
Bug with photonphase ('AbsPhase' object)

### ISSUE THREAD

**Issue by sguillot** [nanograv/PINT#559]
Using photonphase on NICER data and with a simple par file (F0, F1, PEPOCH, POSEPOCH, ...), and I get the following error:

```
Traceback (most recent call last):
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/models/timing_model.py", line 1103, in __getattr__
    return super(Component, self).__getattribute__(name)
AttributeError: 'AbsPhase' object has no attribute 'PEPOCH'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/models/timing_model.py", line 1110, in __getattr__
    % (self.__class__.__name__, name)
AttributeError: 'AbsPhase' object has no attribute 'PEPOCH'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sebastien/Softwares/anaconda3/bin/photonphase", line 11, in <module>
    load_entry_point('pint==0.5.4+360.ga4b33ea', 'console_scripts', 'photonphase')()
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/scripts/photonphase.py", line 192, in main
    iphss, phss = modelin.phase(ts, abs_phase=True)
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/models/timing_model.py", line 580, in phase
    toas
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/models/absolute_phase.py", line 89, in make_TZR_toa
    PEPOCH = self.PEPOCH.quantity.value
  File "/Users/sebastien/Softwares/anaconda3/lib/python3.6/site-packages/pint-0.5.4+360.ga4b33ea-py3.6.egg/pint/models/timing_model.py", line 1117, in __getattr__
    % (self.__class__.__name__, name)
AttributeError: 'AbsPhase' object has no attribute 'PEPOCH'.
```

I'm not sure what can cause this, but this problem does not occur for other different pulsars (with more complex par files).

**Comment by paulray** [comment]
Can you provide the specific par file?
