### ISSUE TITLE
gdbm error

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#579]
This may be an upstream issue that affects PINT.  @juliadeneva found that when she was running PINT scripts simultaneously in two different windows she got the error below occasionally and unpredictably. It seems to be due to multiple processes trying to access the same cache of IERS_B.  I'm not sure if the bug is in astropy our our erfautils
```
Traceback (most recent call last):
  File "/home/paulr/src/NICERsoft/scripts/photon_toa.py", line 426, in <module>
    phss = modelin.phase(ts, abs_phase=True)[1].value  # discard units
  File "/Software/lib/python3.6/site-packages/pint/models/timing_model.py", line 582, in phase
    tz_toa = self.get_TZR_toa(toas)
  File "/Software/lib/python3.6/site-packages/pint/models/absolute_phase.py", line 81, in get_TZR_toa
    planets=toas.planets,
  File "/Software/lib/python3.6/site-packages/pint/toa.py", line 179, in get_TOAs_list
    t.compute_posvels(ephem, planets)
  File "/Software/lib/python3.6/site-packages/pint/toa.py", line 1380, in compute_posvels
    ssb_obs = site.posvel(tdb, ephem)
  File "/Software/lib/python3.6/site-packages/pint/observatory/topo_obs.py", line 323, in posvel
    self.earth_location_itrf(), t, obsname=self.name
  File "/Software/lib/python3.6/site-packages/pint/erfautils.py", line 101, in gcrs_posvel_from_itrf
    iers_b = get_iers_b_up_to_date(mjds.max())
  File "/Software/lib/python3.6/site-packages/pint/erfautils.py", line 27, in get_iers_b_up_to_date
    might_be_old = is_url_in_cache(IERS_B_URL)
  File "/Software/lib/python3.6/site-packages/astropy/utils/data.py", line 1139, in is_url_in_cache
    with shelve.open(urlmapfn) as url2hash:
  File "/Software/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Software/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/Software/lib/python3.6/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable```

**Comment by aarchiba** [comment]
Yes, this is an upstream bug in astropy - the astropy cache locking didn't used to work properly. It does in astropy 4.
