### ISSUE TITLE
Test failing on ltinterface.py

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#72]
I just ran the unit tests and I get failures in ltinterface.py.  In several places is uses `lts`, when I think what is needed is `u.lts`.  For example:
```
             'A1': lts,
```
@vhaasteren can you check on this.  It seems to be your code.

The error I get is:
```
======================================================================
ERROR: Failure: NameError (name 'lts' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/paulr/src/PINT/pint/ltinterface.py", line 60, in <module>
    'A1': lts,
NameError: name 'lts' is not defined
```

**Comment by vhaasteren** [comment]
Hi Paul,

That is correct. That is a very easy fix. However, please note that the ltinterface is 'broken', until units are handled more appropriately in PINT, as in issue 64.

Rutger

**Comment by paulray** [comment]
Right.  Shall I just go ahead and make those edits, or were you planning to?

**Comment by vhaasteren** [comment]
It's like 5 lines, so if you feel so inclined, please do. Otherwise I'll do it in a little bit.

**Comment by paulray** [comment]
OK, fixed
